config/routes.rb
Rails.application.routes.draw do

root "home#index"

get 'products/index', to: 'products#index', as: 'listed'
get '/products/:id/buy', to: 'products#buy', as: 'buy'
get '/cart', to: 'products#cart', as: 'cart'
get '/checkout', to: 'products#checkout', as: 'checkout'

resources :products, path: '/products'
resources :comments, only: [:show, :new, :update]

get '/products.json', to:'products#json', as: 'json'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :initialize_session
  
        def new
          @comment = Comment.new
        end
      
        def edit
          @comment = Comment.find(params[:id])
            redirect_to listed_path
        end
    
        def update
          @comment = Comment.find(params[:id])
            if @comment.update(comment_params)
              redirect_to @comment
            else
              render :edit, status: :unprocessable_entity
            end
            
            message = "You've not submitted any comments!"
            redirect_to listed_path, notice: message
          
        end

        private
          def comment_params
            params.require(:comment).permit(:commenter, :body)
          end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if session[:cart].nil? 
        session[:cart] = [] 
    end
    @cart = session[:cart]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :initialize_session

    def index
      @products = Product.all
    end

    def show
      @product = Product.find(params[:id])
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
    end

    def edit
      @product = Product.find(params[:id])
    end

    def cart
      @cart = session[:cart]
    end

    def checkout
        @cart.each do |product| 
        @product = Product.find(product["id"])
        @product.stock = @product.stock-1
        @product.save
      end
      session[:cart] = nil
      redirect_to listed_path
    end

    def buy
      @product = Product.find(params[:id])
    if @product.stock < 0
        redirect_to listed_path
    else
        session[:cart].append(@product)
        redirect_to listed_path
    end
    end

    def update
      @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy

      redirect_to products_path
    end

    def json
      @products = Product.all
      render json: @products, only: [:id, :title, :description, :price]
    end

  private
    def product_params
      params.require(:product).permit(:title, :body)
    end

    def initialize_session
      if session[:cart].nil? 
        session[:cart] = [] 
    end
    @cart = session[:cart]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/comments/new.html.erb
<div class="container"> 
  <div class="row">
    <div class="col">
      <h1>Add a New Comment</h1>
    </div>
  </div>
</div>

<%@submit_text = "Add New Comment"%>
<%= render "form", comment: @comment %>

app/views/comments/show.html.erb
<div class="container"> 
  <div class="row">
    <div class="col">
      <h1> List of All Comments: </h1><br>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col mb-3">
      <%= form.comments @comments.comment %>
    </div>
  </div>
</div>

app/views/comments/update.html.erb
<div class="container"> 
  <div class="row">
    <div class="col">
      <h1>Edit Your Previous Comment</h1>
    </div>
  </div>
</div>

<%@submit_text = "Update Commentary"%>
<%= render "form", comment: @comment %>

app/views/home/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Our Mission</h1>
            <br>
        </div>
    </div>
    <div class="col">
            <h3>Where we're from?</h3>
            <br>
            <p>Hailing from the great state of Tennessee we pride ourselves on home grown, freshly produced, hand made items. Living up in the mountains for so long has brought us great skill and taught us how to make a whole lot out of just a little. Our products are high quality and durable, we make sure of this.</p>
    </div>
    <div class="col">
            <h3>What we stand for?</h3>
            <br>
            <p>We love our land and we love our people. YOU are our people. Our organization was built on a foundation of unconditional love and infinite worthiness. We will go above and beyond for each of our customers to feel important to us.</p>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "KTH Webstore", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Products", listed_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Cart | #{@cart.length}", cart_path, class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lastwebstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
  <div>Product Title 
    <br>
    <%= form.text_field :title %>
    
  </div>

  <div>Product Description
    <br>
    <%= form.text_area :body %><br>
    
  </div>

  <div>Product Price
    <br>
    <%= form.number_field :price %><br>
    
  </div>

  <div>Product Stock 
    <br>
    <%= form.number_field :stock %><br>
    
  </div>

  <div>Product Image
    <br>
    <%= form.text_field :image %><br>
    
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/cart.html.erb
<div class="container"> 
  <div class="row">
    <div class="col">
            <h1>Your Shopping Cart:</h1>
        </div>
    </div>
  
    <div class="row row-cols-1 row-cols-md-3 g-4">
    <ul>
        <div class="col">
        <% @cart.each do |product| %>
          <li><%= product["title"] %>, <%= product["price"] %></li>
        <% end %>
      </div>
    </ul>
    </div>

    <div class="row">
      <div class="col">
        <h2> Checkout now and your products will arrive in not time! </h2>
        <button class="btn-dark btn-sm" type="button"> <%= link_to "checkout", checkout_path %></button>
      </div>
    </div>

app/views/products/edit.html.erb
<div class="container"> 
  <div class="row">
    <div class="col">
      <h1>Edit Product</h1>
    </div>
  </div>
</div>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
          <h1>Our Products!</h1> 
          <h2>Take a moment to browse. Don't forget to add things you like to your cart!</h2>
        </div>
    </div>
</div>
<ul>
  <% @products.each do |p| %><li>
    
    <%= link_to p.title, p, {:style=>'color:black;', :class => "bold"} %>
    <br>
    <%= image_tag(p.image, {:style => "width: 250px; height: 250px; object-fit: cover;", }) %>
    <br>
    <div class="col" style="text-align: left">
      <%= link_to "Buy", "/products/#{p.id}/buy", class: "btn btn-dark" %>
    </div>
  </li><% end %>
</ul>

app/views/products/new.html.erb
<div class="container"> 
  <div class="row">
    <div class="col">
      <h1>Newly Shelved Items!</h1>
    </div>
  </div>
</div>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>

<p><strong> Description: </strong><%= @product.body %></p>
<p><strong> Price: </strong><%= @product.price %></p>
<p><strong>Stock: </strong><%= @product.stock %></p>
      <% if @product.stock.to_i <= 0 %>
        Out of Stock! We apologize! Check back next month for more inventory.
      <% end %></p>

<%= image_tag(@product.image, {:style => "width: 250px; height: 250px; object-fit: cover;"}) %>
<br>
<button class="btn-dark btn-sm" type="button"><%= link_to "Edit", edit_product_path(@product) %></button>
<button class="btn-dark btn-sm" type="button"><%= link_to "Buy", buy_path(@product)%></button>
<button class="btn-dark btn-sm" type="button"><%= link_to "Destroy", product_path(@product), data: 
                    {turbo_method: :delete,
                    turbo_confirm: "Are you sure?"} %></li></button>